//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Viewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksInLibrary
    {
        public int Id { get; set; }
        public Nullable<int> Id_book { get; set; }
        public Nullable<int> Id_author { get; set; }
        public Nullable<int> Id_customer { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Books Books { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
